version: '3'
services:
  generator:
    build:
      context: .
    working_dir: /usr/src/app
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules

volumes:
  node_modules: {}
